### ISSUE TITLE
Any instruction on running the codes here

### ISSUE THREAD

**Issue by wailoktam** [xiye17/SketchRegex#1]
Hi, I have read your paper and find your work very interesting. Can you provide me some information on running your codes? Thanks.

**Comment by xiye17** [comment]
Hi, it’s true that this repo is still under construction. We have another paper under review which reuses some code from this repo, so we are considering merge the codebase if the other paper gets accepted (Notifications will be out in late Sep). However, I’ll complete or provide more details soon after the results come out anyway.

**Comment by wailoktam** [comment]
Thanks for your prompt reply. Can you tell me the order to run the programs? That would be a big help in the mean time.

**Comment by xiye17** [comment]
Sure. I’ll update the ReadMe this weekend to at least provide commands to run the code. Please stay tuned.

**Comment by wailoktam** [comment]
Hello. Any update? I guess I can also contribute to your work if you make this code runnable for me.

**Comment by xiye17** [comment]
I just pushed some simple instructions for running the code. More details will be added later after the notifications, or maybe the entire repo might be refactored. Should you have any questions please ping me.

**Comment by wailoktam** [comment]
Hi, thanks for your response. I can run your code successfully. However, I cannot find the examples you mention in your paper in the data.  I suppose you combine natural language description of a regex with positive and negative examples of matches to generate a regex. When I look at the dataset folder, I find a natural language description of a regex as the src and a list of symbols representing regexes as the target. Where are the positive and negative examples? Thanks.

**Comment by xiye17** [comment]
They are placed in external/examples/kb13 an external/examples/turk.
The positive/negative examples for each description-regex pair is presented as a single text file, which is used to filter or by the synthesizer.
